name: Production Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Set pull strategy to merge
        run: git config pull.rebase false

      - name: Set Git user identity
        run: |
          git config user.email "nellutlalnrao@gmail.com"
          git config user.name "Nellutla L N Rao"

      - name: Switch to release/app-2 branch
        run: git checkout -B release/app-2

      - name: Pull changes from the release/app-2 branch
        run: git pull --allow-unrelated-histories origin release/app-2

      - name: Clear previous content in release/app-2
        run: |
          git rm -r .
          git commit -m "Clear previous content"
          git push origin release/app-2
          git checkout main

      - name: Pull changes from the main branch
        run: git pull --allow-unrelated-histories origin main

      - name: Build and Deploy to release/app-1
        run: |
          cd app-2
          npm install
          npm run build
          cd ..

      - name: Push to release/app-2 using git subtree
        run: |
          git subtree push --prefix app-2/dist origin release/app-2

      - name: Complete workflow
        run: echo "Workflow completed"
