name: Production Pipeline

on:
  push:
    branches:
      - main  # Replace with the branch you want to trigger the workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14  # Replace with your desired Node.js version

      - name: Build and Deploy to release/app-1
        run: |
          # Install dependencies and build React app
          cd app-1
          npm install
          npm run build
          cd ..

          # Checkout release/app-1 branch
          git checkout release/app-1

          # Copy the contents of the 'dist' folder from main to release/app-1
          rsync -av --exclude='dist' main/ release/app-1/

          # Add and commit changes
          git add .
          git commit -m "Update release/app-1 with latest build"

          # Push changes to release/app-1
          git push origin release/app-1

          # Switch back to the main branch
          git checkout main

      - name: Complete workflow
        run: echo "Workflow completed"
