name: Production Pipeline

on:
  push:
    branches:
      - main  # Replace with the branch you want to trigger the workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14  # Replace with your desired Node.js version

      - name: App-1 Release
        run: |
          cd app-1
          npm install
          npm run build
          cd ..
          git subtree push --prefix app-1/dist origin release/app-1

      - name: App-2 Release
        run: |
          cd app-2
          npm install
          npm run build
          cd ..
          git subtree push --prefix app-2/dist origin release/app-2
    
      - name: Complete workflow
        run: echo "Workflow-1 completed"