name: app-2 production deployment

on:
  push:
    branches:
      - main  # Replace with the branch you want to trigger the workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14  # Replace with your desired Node.js version

      - name: Install dependencies and build
        run: |
          cd app-2
          npm install
          npm run build
          cd ..

      - name: Set pull strategy to merge
        run: git config pull.rebase false

      - name: Set Git user identity
        run: |
          git config user.email "nellutlalnrao@gmail.com"
          git config user.name "Nellutla L N Rao"

      - name: Check Current Branch
        run: |
          current_branch=$(git branch --show-current)
          if [ "$current_branch" == "your-branch-name" ]; then
            echo "Branch exists."
          else
            echo "Branch does not exist."
          fi

      - name: Push changes using subtree
        run: |
          git subtree push --prefix app-2/dist origin release/app-2

      - name: Complete workflow
        run: echo "Workflow-1 completed"
