name: Production Pipeline

on:
  push:
    branches:
      - main  # Replace with the branch you want to trigger the workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14  # Replace with your desired Node.js version

      - name: Set pull strategy to merge
        run: git config pull.rebase false

      - name: Set Git user identity
        run: |
          git config user.email "nellutlalnrao@gmail.com"
          git config user.name "Nellutla L N Rao"

      - name: Pull changes from the remote branch
        run: |
          current_branch=$(git symbolic-ref --short HEAD)
          if [ "$current_branch" == "release/app-2" ]; then
            git checkout release/app-2
          else
            git checkout -b release/app-2
          fi

      - name: Clear previous content in release/app-2
        run: |
          git pull --allow-unrelated-histories origin release/app-2
          git rm -r .
          git commit -m "Clear previous content"
          git push origin release/app-2
          git checkout main

      - name: Build and Deploy to release/app-1
        run: |
          # Install dependencies and build React app
          cd app-1
          npm install
          npm run build
          cd ..

      - name: Push to release/app-2 using git subtree
        run: git subtree push --prefix main/app-2/dist origin release/app-2

      - name: Complete workflow
        run: echo "Workflow completed"
