name: Build and Push Dist Folder

on:
  push:
    branches:
      - main  # Replace with the branch you want to trigger the workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14  # Replace with your desired Node.js version

      - name: Install dependencies
        run: npm install

      - name: Build App
        run: npm run build  # Replace with your build command if needed

      - name: Create and switch to a new branch
        run: |
          git config user.email "nlnrao228@gmail.com"
          git config user.name "Nellutla L N Rao"
          git subtree push --prefix dist origin release

      - name: Push changes to the repository
        uses: softprops/action-gh-release@v1
        with:
          files: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Complete workflow
        run: echo "Workflow completed"
