name: Build and Push Dist Folder

on:
  push:
    branches:
      - main  # Replace with the branch you want to trigger the workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14  # Replace with your desired Node.js version

      - name: Install dependencies
        run: |
          cd app-1
          npm install
          npm run build
          cd ..
          chmod +x deploy.sh
          ./deploy.sh
      
      - name: Complete workflow
        run: echo "Workflow-1 completed"
